# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment_slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
