# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170830_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_upload1',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image_upload2',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image_upload3',
            old_name='file',
            new_name='image',
        ),
    ]
