# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170913_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='middlename',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='surname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
