# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20170918_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
