# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0014_auto_20170918_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_users',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_tags',
            field=models.ManyToManyField(blank=True, related_name='user_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
