# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170919_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='middlename',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='surname',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_users',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='tag single or several users with @username followed by space \n\t\t\t\n e.g @tanya340 @mark for several users\n and @tanya for single user', null=True),
        ),
    ]
