# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20171009_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='followed_genre',
            field=models.ManyToManyField(blank=True, null=True, to='services.Genre'),
        ),
    ]
