# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_user_profile_followed_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='followed_genre',
            field=models.ManyToManyField(blank=True, to='services.Genre'),
        ),
    ]
